
project:
  type: website

website:
  title: "De Nieuwe Stochastentool"
  navbar:
    left:
      - tutorial/tutorial.qmd
      - GUI/GUI.qmd
      - technical_docs/technicaldocumentation.qmd
      - about.qmd
      - literature.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Tutorial"
        contents:
          - tutorial/tutorial.qmd
      - section: "Gebruiksomgeving (GUI)"
        contents:
          - GUI/general.qmd
          - GUI/models.qmd
      - section: "Technische documentatie"
        contents:
          - technical_docs/seizoen.qmd
      - section: "Literatuur"
        contents:
          - literature.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



