
project:
  type: website
  output-dir: ../docs 
  
website:
  title: "De Nieuwe Stochastentool"
  navbar:
    left:
      - tutorial/tutorial.qmd
      - GUI/UserManual.qmd
      - technical_docs/gebiedsreductie.qmd
      - cases/cases.qmd
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Snelstart"
        contents:
          - href: quickstart/inleiding.qmd
            text: "Inleiding"
          - href: quickstart/basisconfiguratie.qmd
            text: "Basisconfiguratie"
          - href: quickstart/modelschematisatie.qmd
            text: "Modelschematisatie"
          - href: quickstart/seizoenen.qmd
            text: "Seizoenen"
          - href: quickstart/volumes.qmd
            text: "Neerslagvolumes"
          - href: quickstart/patronen.qmd
            text: "Neerslagpatronen"
          - href: quickstart/simulaties.qmd
            text: "Simulaties klaarzetten"
          - href: quickstart/simuleren.qmd
            text: "Simulaties doorrekenen"
          - href: quickstart/nabewerken.qmd
            text: "Simulaties nabewerken"
          - href: quickstart/publiceren.qmd
            text: "Resultaat publiceren"
      - section: "Tutorial"
        contents:
          - tutorial/tutorial.qmd
      - section: "Gebruikshandleiding"
        contents:
          - GUI/structure.qmd
          - GUI/workings.qmd
          - GUI/general.qmd
          - GUI/models.qmd
          - GUI/seizoenen.qmd
          - GUI/volume.qmd
          - GUI/patterns.qmd
          - GUI/extra.qmd
          - href: GUI/uitvoer.qmd
            text: Tabblad Uitvoer
          - href: GUI/simulaties.qmd
            text: Tabblad Simulaties
          - href: BAT_RUNR/inleiding.qmd
            text: Simuleren in batch
          - href: GUI/grondwaterclassificatie.qmd
            text: Grondwaterclassificatie
      - section: "Technische documentatie"
        contents:
          - href: technical_docs/gebiedsreductie.qmd
            text: Gebiedsreductiefactor
      - section: "Praktijkcases"
        contents:
          - cases/denbosch.qmd
          - cases/delfland.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lightbox: 
      match: auto
      effect: fade
      desc-position: right
lang: nl

