
project:
  type: website

website:
  title: "De Nieuwe Stochastentool"
  navbar:
    left:
      - tutorial/tutorial.qmd
      - GUI/UserManual.qmd
      - technical_docs/technicaldocumentation.qmd
      - cases/cases.qmd
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Tutorial"
        contents:
          - tutorial/tutorial.qmd
      - section: "Gebruikshandleiding"
        contents:
          - GUI/structure.qmd
          - GUI/workings.qmd
          - GUI/general.qmd
          - GUI/models.qmd
          - GUI/seizoenen.qmd
          - GUI/volume.qmd
          - GUI/patterns.qmd
          - GUI/extra.qmd
          - href: GUI/uitvoer.qmd
            text: Tabblad Uitvoer
          - href: GUI/simulaties.qmd
            text: Tabblad Simulaties
          - href: BAT_RUNR/inleiding.qmd
            text: Simuleren in batch
      - section: "Technische documentatie"
      - section: "Praktijkcases"
        contents:
          - cases/denbosch.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



