'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DateFormatting() As String
            Get
                Return CType(Me("DateFormatting"),String)
            End Get
            Set
                Me("DateFormatting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Delimiter() As String
            Get
                Return CType(Me("Delimiter"),String)
            End Get
            Set
                Me("Delimiter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SeriesName() As String
            Get
                Return CType(Me("SeriesName"),String)
            End Get
            Set
                Me("SeriesName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CSVFile() As String
            Get
                Return CType(Me("CSVFile"),String)
            End Get
            Set
                Me("CSVFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Duration() As String
            Get
                Return CType(Me("Duration"),String)
            End Get
            Set
                Me("Duration") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MaxAantalVerhoogdLaagwater() As String
            Get
                Return CType(Me("MaxAantalVerhoogdLaagwater"),String)
            End Get
            Set
                Me("MaxAantalVerhoogdLaagwater") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AantalAmplitudeKlassen() As String
            Get
                Return CType(Me("AantalAmplitudeKlassen"),String)
            End Get
            Set
                Me("AantalAmplitudeKlassen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Uitloop() As String
            Get
                Return CType(Me("Uitloop"),String)
            End Get
            Set
                Me("Uitloop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PercentageDuur() As String
            Get
                Return CType(Me("PercentageDuur"),String)
            End Get
            Set
                Me("PercentageDuur") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SobekDir() As String
            Get
                Return CType(Me("SobekDir"),String)
            End Get
            Set
                Me("SobekDir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Classes() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Classes"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("Classes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Percentiles() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Percentiles"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("Percentiles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ElevationClasses() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ElevationClasses"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("ElevationClasses") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("laagwater")>  _
        Public Property TidalComponent() As String
            Get
                Return CType(Me("TidalComponent"),String)
            End Get
            Set
                Me("TidalComponent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property AmplitudeClasses() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("AmplitudeClasses"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("AmplitudeClasses") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property GroundwaterClasses() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("GroundwaterClasses"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("GroundwaterClasses") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TidalClassificationAdvanced() As Boolean
            Get
                Return CType(Me("TidalClassificationAdvanced"),Boolean)
            End Get
            Set
                Me("TidalClassificationAdvanced") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GRIB2")>  _
        Public Property HIRLAMFORMAT() As String
            Get
                Return CType(Me("HIRLAMFORMAT"),String)
            End Get
            Set
                Me("HIRLAMFORMAT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EPSG:2993")>  _
        Public Property HIRLAMPROJECTION() As String
            Get
                Return CType(Me("HIRLAMPROJECTION"),String)
            End Get
            Set
                Me("HIRLAMPROJECTION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("13")>  _
        Public Property HIRLAMPRECINITBAND() As Integer
            Get
                Return CType(Me("HIRLAMPRECINITBAND"),Integer)
            End Get
            Set
                Me("HIRLAMPRECINITBAND") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property HIRLAMPRECPREDICTBAND() As String
            Get
                Return CType(Me("HIRLAMPRECPREDICTBAND"),String)
            End Get
            Set
                Me("HIRLAMPRECPREDICTBAND") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\temp")>  _
        Public Property HIRLAMSOURCEDIR() As String
            Get
                Return CType(Me("HIRLAMSOURCEDIR"),String)
            End Get
            Set
                Me("HIRLAMSOURCEDIR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Datum/Tijd")>  _
        Public Property DateHeader() As String
            Get
                Return CType(Me("DateHeader"),String)
            End Get
            Set
                Me("DateHeader") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("261")>  _
        Public Property ValHeader() As String
            Get
                Return CType(Me("ValHeader"),String)
            End Get
            Set
                Me("ValHeader") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\temp\temp.txt")>  _
        Public Property FileName() As String
            Get
                Return CType(Me("FileName"),String)
            End Get
            Set
                Me("FileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PRECIPITATION")>  _
        Public Property DataType() As String
            Get
                Return CType(Me("DataType"),String)
            End Get
            Set
                Me("DataType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("day")>  _
        Public Property TimeStep() As String
            Get
                Return CType(Me("TimeStep"),String)
            End Get
            Set
                Me("TimeStep") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CatchmentID() As String
            Get
                Return CType(Me("CatchmentID"),String)
            End Get
            Set
                Me("CatchmentID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SourceFile() As String
            Get
                Return CType(Me("SourceFile"),String)
            End Get
            Set
                Me("SourceFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TargetFile() As String
            Get
                Return CType(Me("TargetFile"),String)
            End Get
            Set
                Me("TargetFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ScriptID() As String
            Get
                Return CType(Me("ScriptID"),String)
            End Get
            Set
                Me("ScriptID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BaseflowFilter_k() As String
            Get
                Return CType(Me("BaseflowFilter_k"),String)
            End Get
            Set
                Me("BaseflowFilter_k") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BaseflowFilter_w() As String
            Get
                Return CType(Me("BaseflowFilter_w"),String)
            End Get
            Set
                Me("BaseflowFilter_w") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ParametersChecked() As String
            Get
                Return CType(Me("ParametersChecked"),String)
            End Get
            Set
                Me("ParametersChecked") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChartTitle() As String
            Get
                Return CType(Me("ChartTitle"),String)
            End Get
            Set
                Me("ChartTitle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property XAxisTitle() As String
            Get
                Return CType(Me("XAxisTitle"),String)
            End Get
            Set
                Me("XAxisTitle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property YAxisTitle() As String
            Get
                Return CType(Me("YAxisTitle"),String)
            End Get
            Set
                Me("YAxisTitle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2008/01/01 00:00:00")>  _
        Public Property StartDateStr() As String
            Get
                Return CType(Me("StartDateStr"),String)
            End Get
            Set
                Me("StartDateStr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2012/01/01 00:00:00")>  _
        Public Property EndDateStr() As String
            Get
                Return CType(Me("EndDateStr"),String)
            End Get
            Set
                Me("EndDateStr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Postprocessing() As String
            Get
                Return CType(Me("Postprocessing"),String)
            End Get
            Set
                Me("Postprocessing") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ContainsHeader() As Boolean
            Get
                Return CType(Me("ContainsHeader"),Boolean)
            End Get
            Set
                Me("ContainsHeader") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DatePickerValue() As Date
            Get
                Return CType(Me("DatePickerValue"),Date)
            End Get
            Set
                Me("DatePickerValue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ID() As String
            Get
                Return CType(Me("ID"),String)
            End Get
            Set
                Me("ID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PAR() As String
            Get
                Return CType(Me("PAR"),String)
            End Get
            Set
                Me("PAR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3600")>  _
        Public Property TimestepSizeSeconds() As Integer
            Get
                Return CType(Me("TimestepSizeSeconds"),Integer)
            End Get
            Set
                Me("TimestepSizeSeconds") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CustomID() As Boolean
            Get
                Return CType(Me("CustomID"),Boolean)
            End Get
            Set
                Me("CustomID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CustomPAR() As Boolean
            Get
                Return CType(Me("CustomPAR"),Boolean)
            End Get
            Set
                Me("CustomPAR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CustomStartDate() As Boolean
            Get
                Return CType(Me("CustomStartDate"),Boolean)
            End Get
            Set
                Me("CustomStartDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TimeFormatting() As String
            Get
                Return CType(Me("TimeFormatting"),String)
            End Get
            Set
                Me("TimeFormatting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Multiplier() As Double
            Get
                Return CType(Me("Multiplier"),Double)
            End Get
            Set
                Me("Multiplier") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CustomSeriesID() As Boolean
            Get
                Return CType(Me("CustomSeriesID"),Boolean)
            End Get
            Set
                Me("CustomSeriesID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologySubcatchmentsSF() As String
            Get
                Return CType(Me("TopologySubcatchmentsSF"),String)
            End Get
            Set
                Me("TopologySubcatchmentsSF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologySubcatchmentsIDField() As String
            Get
                Return CType(Me("TopologySubcatchmentsIDField"),String)
            End Get
            Set
                Me("TopologySubcatchmentsIDField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologySubcatchmentsWPField() As String
            Get
                Return CType(Me("TopologySubcatchmentsWPField"),String)
            End Get
            Set
                Me("TopologySubcatchmentsWPField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologySubcatchmentsZPField() As String
            Get
                Return CType(Me("TopologySubcatchmentsZPField"),String)
            End Get
            Set
                Me("TopologySubcatchmentsZPField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyWeirsSF() As String
            Get
                Return CType(Me("TopologyWeirsSF"),String)
            End Get
            Set
                Me("TopologyWeirsSF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyWeirsIDField() As String
            Get
                Return CType(Me("TopologyWeirsIDField"),String)
            End Get
            Set
                Me("TopologyWeirsIDField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyWeirsFromField() As String
            Get
                Return CType(Me("TopologyWeirsFromField"),String)
            End Get
            Set
                Me("TopologyWeirsFromField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyWeirsToField() As String
            Get
                Return CType(Me("TopologyWeirsToField"),String)
            End Get
            Set
                Me("TopologyWeirsToField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property WeirCrestWidthField() As String
            Get
                Return CType(Me("WeirCrestWidthField"),String)
            End Get
            Set
                Me("WeirCrestWidthField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyPumpsIDField() As String
            Get
                Return CType(Me("TopologyPumpsIDField"),String)
            End Get
            Set
                Me("TopologyPumpsIDField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyPumpsFromField() As String
            Get
                Return CType(Me("TopologyPumpsFromField"),String)
            End Get
            Set
                Me("TopologyPumpsFromField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyPumpsToField() As String
            Get
                Return CType(Me("TopologyPumpsToField"),String)
            End Get
            Set
                Me("TopologyPumpsToField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PumpCapField() As String
            Get
                Return CType(Me("PumpCapField"),String)
            End Get
            Set
                Me("PumpCapField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyPumpsSF() As String
            Get
                Return CType(Me("TopologyPumpsSF"),String)
            End Get
            Set
                Me("TopologyPumpsSF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyCulvertsSF() As String
            Get
                Return CType(Me("TopologyCulvertsSF"),String)
            End Get
            Set
                Me("TopologyCulvertsSF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyCulvertsIDField() As String
            Get
                Return CType(Me("TopologyCulvertsIDField"),String)
            End Get
            Set
                Me("TopologyCulvertsIDField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyCulvertsFromField() As String
            Get
                Return CType(Me("TopologyCulvertsFromField"),String)
            End Get
            Set
                Me("TopologyCulvertsFromField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyCulvertsToField() As String
            Get
                Return CType(Me("TopologyCulvertsToField"),String)
            End Get
            Set
                Me("TopologyCulvertsToField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CulvertsWidthField() As String
            Get
                Return CType(Me("CulvertsWidthField"),String)
            End Get
            Set
                Me("CulvertsWidthField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologySiphonsSF() As String
            Get
                Return CType(Me("TopologySiphonsSF"),String)
            End Get
            Set
                Me("TopologySiphonsSF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologySiphonsIDField() As String
            Get
                Return CType(Me("TopologySiphonsIDField"),String)
            End Get
            Set
                Me("TopologySiphonsIDField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologySiphonsFromField() As String
            Get
                Return CType(Me("TopologySiphonsFromField"),String)
            End Get
            Set
                Me("TopologySiphonsFromField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologySiphonsToField() As String
            Get
                Return CType(Me("TopologySiphonsToField"),String)
            End Get
            Set
                Me("TopologySiphonsToField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SiphonsWidthField() As String
            Get
                Return CType(Me("SiphonsWidthField"),String)
            End Get
            Set
                Me("SiphonsWidthField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologySubcatchmentsOpenConnectionField() As String
            Get
                Return CType(Me("TopologySubcatchmentsOpenConnectionField"),String)
            End Get
            Set
                Me("TopologySubcatchmentsOpenConnectionField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ElevationGrid() As String
            Get
                Return CType(Me("ElevationGrid"),String)
            End Get
            Set
                Me("ElevationGrid") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PumpCapUnits() As String
            Get
                Return CType(Me("PumpCapUnits"),String)
            End Get
            Set
                Me("PumpCapUnits") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CulvertsHeightField() As String
            Get
                Return CType(Me("CulvertsHeightField"),String)
            End Get
            Set
                Me("CulvertsHeightField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CulvertsLengthField() As String
            Get
                Return CType(Me("CulvertsLengthField"),String)
            End Get
            Set
                Me("CulvertsLengthField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CulvertsInvertUpField() As String
            Get
                Return CType(Me("CulvertsInvertUpField"),String)
            End Get
            Set
                Me("CulvertsInvertUpField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CulvertsInvertDownField() As String
            Get
                Return CType(Me("CulvertsInvertDownField"),String)
            End Get
            Set
                Me("CulvertsInvertDownField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SiphonsHeightField() As String
            Get
                Return CType(Me("SiphonsHeightField"),String)
            End Get
            Set
                Me("SiphonsHeightField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SiphonsLengthField() As String
            Get
                Return CType(Me("SiphonsLengthField"),String)
            End Get
            Set
                Me("SiphonsLengthField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SiphonsInvertUpField() As String
            Get
                Return CType(Me("SiphonsInvertUpField"),String)
            End Get
            Set
                Me("SiphonsInvertUpField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SiphonsInvertDownField() As String
            Get
                Return CType(Me("SiphonsInvertDownField"),String)
            End Get
            Set
                Me("SiphonsInvertDownField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChannelsShapefile() As String
            Get
                Return CType(Me("ChannelsShapefile"),String)
            End Get
            Set
                Me("ChannelsShapefile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MaxChannelWidth() As Double
            Get
                Return CType(Me("MaxChannelWidth"),Double)
            End Get
            Set
                Me("MaxChannelWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseWeirSF() As Boolean
            Get
                Return CType(Me("UseWeirSF"),Boolean)
            End Get
            Set
                Me("UseWeirSF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UsePumpSF() As Boolean
            Get
                Return CType(Me("UsePumpSF"),Boolean)
            End Get
            Set
                Me("UsePumpSF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseCulvertSF() As Boolean
            Get
                Return CType(Me("UseCulvertSF"),Boolean)
            End Get
            Set
                Me("UseCulvertSF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseSiphonSF() As Boolean
            Get
                Return CType(Me("UseSiphonSF"),Boolean)
            End Get
            Set
                Me("UseSiphonSF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseOrificeSF() As Boolean
            Get
                Return CType(Me("UseOrificeSF"),Boolean)
            End Get
            Set
                Me("UseOrificeSF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyOrificeSF() As String
            Get
                Return CType(Me("TopologyOrificeSF"),String)
            End Get
            Set
                Me("TopologyOrificeSF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyOrificesIDField() As String
            Get
                Return CType(Me("TopologyOrificesIDField"),String)
            End Get
            Set
                Me("TopologyOrificesIDField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyOrificesFromField() As String
            Get
                Return CType(Me("TopologyOrificesFromField"),String)
            End Get
            Set
                Me("TopologyOrificesFromField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TopologyOrificesToField() As String
            Get
                Return CType(Me("TopologyOrificesToField"),String)
            End Get
            Set
                Me("TopologyOrificesToField") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property UnderwaterProfileRoughness() As Double
            Get
                Return CType(Me("UnderwaterProfileRoughness"),Double)
            End Get
            Set
                Me("UnderwaterProfileRoughness") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsd=""http://www.w3."& _ 
            "org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>2010040101</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>2012033123</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property ReplaceString() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ReplaceString"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("ReplaceString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsd=""http://www.w3."& _ 
            "org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>STARTDATE</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>ENDDATE</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property ReplaceStringBy() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ReplaceStringBy"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("ReplaceStringBy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsd=""http://www.w3."& _ 
            "org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>yyyyMMddHH</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>yyyyMMddHH</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property ReplaceStringFormat() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ReplaceStringFormat"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("ReplaceStringFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsd=""http://www.w3."& _ 
            "org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>all</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>50</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>600</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>0.5"& _ 
            "</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>1.0</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property LastParVals() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("LastParVals"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("LastParVals") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property HBVReportPath() As String
            Get
                Return CType(Me("HBVReportPath"),String)
            End Get
            Set
                Me("HBVReportPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property HBVModelDir() As String
            Get
                Return CType(Me("HBVModelDir"),String)
            End Get
            Set
                Me("HBVModelDir") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.STOCHLIB.My.MySettings
            Get
                Return Global.STOCHLIB.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
